In [14]:
import numpy as np
from scipy import sparse

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [16]:
eye = np.eye(4)
print("Numpy array ;\n{}".format(eye))

Numpy array ;
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
